### PR TITLE
Use admonition boxes.

### PR DESCRIPTION
**Pull request by bfabio**

### CODE REVIEW

**Comment by bfabio** [comment]
Warning: I was not able to test this because of #20

**Comment by bfabio** [comment]
@pdavide WDYT?

**Comment by pdavide** [comment]
@bfabio your PR is visibile in private mode at https://docs.italia.it/docs/writing-toolkit/it/adm_boxes/ so you can see your changes in live documentation.

**Comment by bfabio** [comment]
Looks good.

image

**Pull request merged**
